/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emuseo.Vista;

import emuseo.Controlador.controlCRUDAutor;
import emuseo.Controlador.controlCRUDNacionalidad;
import emuseo.Modelo.Autores;
import emuseo.Modelo.Nacionalidad;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alvar
 */
public class frmAutores extends javax.swing.JInternalFrame {

    //Elemento para saber la fila seleccionada
    private int contam = 0;
    private int fila = -1;
    //Elemento para almacenar el codigo
    private int cod;
    //Instancia a ControlCRUDGalerias
    controlCRUDAutor crud = new controlCRUDAutor();
    controlCRUDNacionalidad crud2 = new controlCRUDNacionalidad();
    DefaultTableModel tabla = new DefaultTableModel();
    //Definir un objeto de tipo combobox
    DefaultComboBoxModel datos = new DefaultComboBoxModel();

    //Metodo para mostrar lista de Paises
    private void llenarNacionalidad() {
        ArrayList<Nacionalidad> lista2 = crud2.mostrarNacionalidad("");
        for (Nacionalidad p : lista2) {
            p = new Nacionalidad(p.getNombreNacionalidad());
            datos.addElement(p);
        }
        nacionalidad.setModel(datos);
    }

    //Metodo para llenar la tabla
    private void llenartabla() {
        //Indicar que empezamos por la columna 0
        tabla.setColumnCount(0);
        //Agregar columnas
        tabla.addColumn("Id Autor");
        tabla.addColumn("Nombre Autor");
        tabla.addColumn("Fecha Nacimiento");
        tabla.addColumn("Fecha Defuncion");
        tabla.addColumn("Nacionalidad");
        //Recibir el ArrayList
        ArrayList<Autores> lista = crud.mostrarAutores("");
        //Determinar la cantidad de filas de la tabla
        tabla.setNumRows(lista.size());
        //Llenar la tabla
        for (int i = 0; i < lista.size(); i++) {
            tabla.setValueAt(lista.get(i).getCodigoAutor(), i, 0);
            tabla.setValueAt(lista.get(i).getNombreAutor(), i, 1);
            tabla.setValueAt(lista.get(i).getFechaNacimientoAutor(), i, 2);
            tabla.setValueAt(lista.get(i).getFechaDefuncionAutor(), i, 3);
            tabla.setValueAt(lista.get(i).getNombreNacionalidad(), i, 4);
        }
        //Enviar los datos a la vista(tabla)
        jTable1.setModel(tabla);
    }

    /**
     * Creates new form frmNacionalidadNuevo
     */
    public frmAutores() {
        initComponents();
        llenartabla();
        llenarNacionalidad();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombreAutor = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        fNacimiento = new com.toedter.calendar.JDateChooser();
        fDefuncion = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        nacionalidad = new javax.swing.JComboBox<>();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Nombre Autor:");

        jLabel2.setText("FechaNacimiento:");

        jButton1.setText("Grabar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setText("FechaDefuncion:");

        jLabel4.setText("Nacionalidad:");

        nacionalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nombreAutor, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(fNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fDefuncion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nacionalidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombreAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jButton2))
                    .addComponent(fNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(fDefuncion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Casting
        Nacionalidad p = (Nacionalidad) nacionalidad.getSelectedItem();
        if (contam > 0) {
            String fecha3 = new SimpleDateFormat("yyyy/MM/dd").format(fNacimiento.getDate());
            String fecha4 = new SimpleDateFormat("yyyy/MM/dd").format(fDefuncion.getDate());
            contam = 0;
            crud.modificarAutor(cod, nombreAutor.getText(), fecha3, fecha4, p.getCodigoNacionalidad());
            JOptionPane.showMessageDialog(this, "Se ha Modificado.");
        } else {
            String fecha1 = new SimpleDateFormat("yyyy/MM/dd").format(fNacimiento.getDate());
            String fecha2 = new SimpleDateFormat("yyyy/MM/dd").format(fDefuncion.getDate());
            //Se crea
            crud.insertarAutor(nombreAutor.getText(), fecha1, fecha2, p.getCodigoNacionalidad());
            //Se avisa
            JOptionPane.showMessageDialog(this, "Se ha Grabado.");
        }
        //Limpiar las cajas
        nombreAutor.setText("");
        fNacimiento.setDateFormatString("");
        fDefuncion.setDateFormatString("");
        //Cargar los datos en la tabla
        llenartabla();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (fila > -1) {
            nombreAutor.setText(String.valueOf(jTable1.getValueAt(fila, 1)));
            cod = Integer.parseInt(String.valueOf(jTable1.getValueAt(fila, 0)));
            fNacimiento.setDateFormatString(String.valueOf(jTable1.getValueAt(fila, 2)));
            fDefuncion.setDateFormatString(String.valueOf(jTable1.getValueAt(fila, 3)));
            fila = -1;
            contam++;

        } else {
            JOptionPane.showMessageDialog(this, "Debe Seleccionar un Registro", "Advertencia", JOptionPane.OK_OPTION + JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (fila > -1) {
            int res = JOptionPane.showConfirmDialog(this, "¿Desea eliminar al Autor " + String.valueOf(jTable1.getValueAt(fila, 1))
                    + " ?", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
            if (res == 0) {
                crud.eliminarAutor(Integer.parseInt(String.valueOf(jTable1.getValueAt(fila, 0))));
                llenartabla();
            }
            fila = -1;
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un Registro", "Advertencia", JOptionPane.OK_OPTION + JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser fDefuncion;
    private com.toedter.calendar.JDateChooser fNacimiento;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> nacionalidad;
    private javax.swing.JTextField nombreAutor;
    // End of variables declaration//GEN-END:variables
}
