/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emuseo.Vista;

import emuseo.Controlador.controlCRUDNacionalidad;
import emuseo.Controlador.controlCRUDPais;
import emuseo.Modelo.Nacionalidad;
import emuseo.Modelo.Pais;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alvar
 */
public class frmNacionalidad extends javax.swing.JInternalFrame {

    //Elemento para saber la fila seleccionada
    private int contam = 0;
    private int fila = -1;
    //Elemento para almacenar el codigo
    private int cod;
    //Instancia a ControlCRUDGalerias
    controlCRUDNacionalidad crud = new controlCRUDNacionalidad();
    controlCRUDPais crud2 = new controlCRUDPais();
    DefaultTableModel tabla = new DefaultTableModel();
    //Definir un objeto de tipo combobox
    DefaultComboBoxModel datos = new DefaultComboBoxModel();

    //Metodo para mostrar lista de Paises
    private void llenarpaises() {
        ArrayList<Pais> lista = crud2.mostrarPais("");
        for (Pais p : lista) {
            p = new Pais(p.getNombrePais());
            datos.addElement(p);
        }
        pais.setModel(datos);
    }

    //Metodo para llenar la tabla
    private void llenartabla() {
        //Indicar que empezamos por la columna 0
        tabla.setColumnCount(0);
        //Agregar columnas
        tabla.addColumn("Id Nacionalidad");
        tabla.addColumn("Nacionalidad");
        tabla.addColumn("Pais");
        //Recibir el ArrayList
        ArrayList<Nacionalidad> lista = crud.mostrarNacionalidad("");
        //Determinar la cantidad de filas de la tabla
        tabla.setNumRows(lista.size());
        //Llenar la tabla
        for (int i = 0; i < lista.size(); i++) {
            tabla.setValueAt(lista.get(i).getCodigoNacionalidad(), i, 0);
            tabla.setValueAt(lista.get(i).getNombreNacionalidad(), i, 1);
            tabla.setValueAt(lista.get(i).getNombrePais(), i, 2);
        }
        //Enviar los datos a la vista(tabla)
        jTable1.setModel(tabla);
    }

    /**
     * Creates new form frmNacionalidadNuevo
     */
    public frmNacionalidad() {
        initComponents();
        llenartabla();
        llenarpaises();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombreNacionalidad = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        pais = new javax.swing.JComboBox<>();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Nacionalidad:");

        jLabel2.setText("Pais:");

        jButton1.setText("Nuevo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        pais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nombreNacionalidad, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(pais, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombreNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton2)
                    .addComponent(pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        fila = jTable1.rowAtPoint(evt.getPoint());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Casting
        Pais p = (Pais) pais.getSelectedItem();
        if (contam > 0) {
            contam = 0;
            crud.modificarNacionalidad(cod, nombreNacionalidad.getText(), p.getCodigoPais());
            JOptionPane.showMessageDialog(this, "Se ha Modificado.");
            //Limpiar las cajas
            nombreNacionalidad.setText("");
            //Cargar los datos en la tabla
            llenartabla();
        } else {
            //Se crea
            crud.insertarNacionalidad(nombreNacionalidad.getText(), p.getCodigoPais());
            //Se avisa
            JOptionPane.showMessageDialog(this, "Se ha Grabado.");
            //Limpiar las cajas
            nombreNacionalidad.setText("");
            //Cargar los datos en la tabla
            llenartabla();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (fila > -1) {
            int res = JOptionPane.showConfirmDialog(this, "¿Desea eliminar la Nacionalidad " + String.valueOf(jTable1.getValueAt(fila, 1))
                    + " ?", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
            if (res == 0) {
                crud.eliminarNacionalidad(Integer.parseInt(String.valueOf(jTable1.getValueAt(fila, 0))));
                llenartabla();
            }
            fila = -1;
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un Registro", "Advertencia", JOptionPane.OK_OPTION + JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         if (fila > -1) {
            nombreNacionalidad.setText(String.valueOf(jTable1.getValueAt(fila, 1)));
            cod = Integer.parseInt(String.valueOf(jTable1.getValueAt(fila, 0)));
            fila = -1;
            contam++;
     
        } else {
            JOptionPane.showMessageDialog(this, "Debe Seleccionar un Registro", "Advertencia", JOptionPane.OK_OPTION + JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nombreNacionalidad;
    private javax.swing.JComboBox<String> pais;
    // End of variables declaration//GEN-END:variables
}
