/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emuseo.Vista;

import emuseo.Controlador.controlCRUDAutor;
import emuseo.Controlador.controlCRUDObraDeArte;
import emuseo.Controlador.controlCRUDTipoOA;
import emuseo.Modelo.Autores;
import emuseo.Modelo.Nacionalidad;
import emuseo.Modelo.ObraDeArte;
import emuseo.Modelo.TipoOA;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alvar
 */
public class frmObrasDeArte extends javax.swing.JInternalFrame {

    //Elemento para saber la fila seleccionada
    private int contam = 0;
    private int fila = -1;
    //Elemento para almacenar el codigo
    private int cod;
    //Instancia a ControlCRUDGalerias
    controlCRUDObraDeArte crud = new controlCRUDObraDeArte();
    controlCRUDAutor crud2 = new controlCRUDAutor();
    controlCRUDTipoOA crud3 = new controlCRUDTipoOA();
    DefaultTableModel tabla = new DefaultTableModel();
    //Definir un objeto de tipo combobox
    DefaultComboBoxModel datos = new DefaultComboBoxModel();
    DefaultComboBoxModel datos2 = new DefaultComboBoxModel();

    //Metodo para mostrar lista de Paises
    private void llenarAutor() {
        ArrayList<Autores> lista2 = crud2.mostrarAutores("");
        for (Autores p : lista2) {
            p = new Autores(p.getNombreNacionalidad());
            datos.addElement(p);
        }
        autor.setModel(datos);
    }

    private void llenarTipoOA() {
        ArrayList<TipoOA> lista3 = crud2.mostrarAutores("");
        for (TipoOA p : lista3) {
            p = new TipoOA(p.getDescripcionTipoOA());
            datos2.addElement(p);
        }
        tipo.setModel(datos2);
    }

    //Metodo para llenar la tabla
    private void llenartabla() {
        //Indicar que empezamos por la columna 0
        tabla.setColumnCount(0);
        //Agregar columnas
        tabla.addColumn("Id Obra");
        tabla.addColumn("Titulo");
        tabla.addColumn("Fecha Creacion");
        tabla.addColumn("Fecha Llegada");
        tabla.addColumn("Autor");
        tabla.addColumn("Tipo");
        //Recibir el ArrayList
        ArrayList<ObraDeArte> lista = crud.mostrarObra("");
        //Determinar la cantidad de filas de la tabla
        tabla.setNumRows(lista.size());
        //Llenar la tabla
        for (int i = 0; i < lista.size(); i++) {
            tabla.setValueAt(lista.get(i).getCodigoObraArte(), i, 0);
            tabla.setValueAt(lista.get(i).getTituloObra(), i, 1);
            tabla.setValueAt(lista.get(i).getfCreacionObra(), i, 2);
            tabla.setValueAt(lista.get(i).getfLlegadaObra(), i, 3);
            tabla.setValueAt(lista.get(i).getNombreAutor(), i, 4);
            tabla.setValueAt(lista.get(i).getDescripcionTipoOA(), i, 5);
        }
        //Enviar los datos a la vista(tabla)
        jTable1.setModel(tabla);
    }

    /**
     * Creates new form frmNacionalidadNuevo
     */
    public frmObrasDeArte() {
        initComponents();
        llenarAutor();
        llenarTipoOA();
        llenartabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombreNacionalidad = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        autor = new javax.swing.JComboBox<>();
        fechaCreacion = new com.toedter.calendar.JDateChooser();
        fechaLlegada = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        tipo = new javax.swing.JComboBox<>();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Titulo Obra:");

        jLabel2.setText("Fecha Creacion:");

        jButton1.setText("Grabar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Modificar");

        jButton3.setText("Eliminar");

        jLabel3.setText("Fecha Llegada:");

        jLabel5.setText("Autor:");

        autor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Tipo:");

        tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nombreNacionalidad, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(autor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fechaCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombreNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jButton2))
                    .addComponent(fechaCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechaLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(autor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Casting
        Autores p = (Autores) autor.getSelectedItem();
        if (contam > 0) {
            String fecha3 = new SimpleDateFormat("yyyy/MM/dd").format(fNacimiento.getDate());
            String fecha4 = new SimpleDateFormat("yyyy/MM/dd").format(fDefuncion.getDate());
            contam = 0;
            crud.modificarAutor(cod, nombreAutor.getText(), fecha3, fecha4, p.getCodigoNacionalidad());
            JOptionPane.showMessageDialog(this, "Se ha Modificado.");
        } else {
            String fecha1 = new SimpleDateFormat("yyyy/MM/dd").format(fNacimiento.getDate());
            String fecha2 = new SimpleDateFormat("yyyy/MM/dd").format(fDefuncion.getDate());
            //Se crea
            crud.insertarAutor(nombreAutor.getText(), fecha1, fecha2, p.getCodigoNacionalidad());
            //Se avisa
            JOptionPane.showMessageDialog(this, "Se ha Grabado.");
        }
        //Limpiar las cajas
        nombreutor.setText("");
        fNacimiento.setDateFormatString("");
        fDefuncion.setDateFormatString("");
        //Cargar los datos en la tabla
        llenartabla();

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> autor;
    private com.toedter.calendar.JDateChooser fechaCreacion;
    private com.toedter.calendar.JDateChooser fechaLlegada;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nombreNacionalidad;
    private javax.swing.JComboBox<String> tipo;
    // End of variables declaration//GEN-END:variables
}
