/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emuseo.Vista;

import java.awt.Dimension;
import javax.swing.DesktopManager;
import javax.swing.JInternalFrame;
import javax.swing.UIManager;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;

/**
 *
 * @author 19875861-2
 */
public class frmPrincipal extends javax.swing.JFrame {

    public static int privilegio = 0;

    public static void centrar(JInternalFrame frm) {
        Dimension desktopSize = visor.getSize();
        Dimension FrameSize = frm.getSize();
        frm.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        frm.show();
    }

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        //Maximizar
        this.setExtendedState(6);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        iniciar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        cerrar = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        mensajebien = new javax.swing.JLabel();
        visor = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        catalogo = new javax.swing.JMenu();
        mantencion = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jToolBar1.setBackground(new java.awt.Color(0, 0, 0));
        jToolBar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jToolBar1.setRollover(true);

        iniciar.setBackground(new java.awt.Color(102, 102, 102));
        iniciar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        iniciar.setForeground(new java.awt.Color(255, 255, 255));
        iniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/login.png"))); // NOI18N
        iniciar.setText("Login");
        iniciar.setFocusable(false);
        iniciar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        iniciar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarActionPerformed(evt);
            }
        });
        jToolBar1.add(iniciar);
        jToolBar1.add(jSeparator2);
        jToolBar1.add(jSeparator4);

        cerrar.setBackground(new java.awt.Color(102, 102, 102));
        cerrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cerrar.setForeground(new java.awt.Color(255, 255, 255));
        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar.png"))); // NOI18N
        cerrar.setText("Cerrar Sesión");
        cerrar.setEnabled(false);
        cerrar.setFocusable(false);
        cerrar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        cerrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });
        jToolBar1.add(cerrar);

        jPanel1.add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jToolBar2.setBackground(new java.awt.Color(102, 102, 102));
        jToolBar2.setBorder(new javax.swing.border.MatteBorder(null));
        jToolBar2.setRollover(true);

        mensajebien.setForeground(new java.awt.Color(255, 255, 255));
        mensajebien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario-icono-6969-32.png"))); // NOI18N
        jToolBar2.add(mensajebien);

        jPanel1.add(jToolBar2, java.awt.BorderLayout.PAGE_END);

        visor.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/68434943-wallpapers-hd-wallpapers.jpg"))); // NOI18N

        visor.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout visorLayout = new javax.swing.GroupLayout(visor);
        visor.setLayout(visorLayout);
        visorLayout.setHorizontalGroup(
            visorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        visorLayout.setVerticalGroup(
            visorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(visor, java.awt.BorderLayout.CENTER);

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 204));

        catalogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aaaaa.png"))); // NOI18N
        catalogo.setText("Catálogo");
        catalogo.setEnabled(false);
        catalogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                catalogoMouseClicked(evt);
            }
        });
        jMenuBar1.add(catalogo);

        mantencion.setText("Mantención");
        mantencion.setEnabled(false);
        jMenuBar1.add(mantencion);

        jMenu1.setText("Prestamo y Devolución");
        jMenu1.setEnabled(false);
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarActionPerformed

        //llamar formulario Login
        frmLoginAdmin frm = new frmLoginAdmin();
        visor.add(frm);
        centrar(frm);
    }//GEN-LAST:event_iniciarActionPerformed

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        //llamar formulario Login
        frmLoginAdmin frm = new frmLoginAdmin();
        visor.add(frm);
        centrar(frm);
        cerrar.setEnabled(false);
        iniciar.setEnabled(true);
        try {
            JInternalFrame frames[] = visor.getAllFrames();
            DesktopManager dm = visor.getDesktopManager();
            for (int i = 0; i < frames.length; i++) {
                dm.closeFrame(frames[i]);
                frames[i].setClosed(false);
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_cerrarActionPerformed

    private void catalogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_catalogoMouseClicked
        if (privilegio >= 1) {
            if (jMenuBar1.isEnabled()) {
                frmCatalogo frm = new frmCatalogo();
                visor.add(frm);
                frm.show();
                try {
                    frm.setMaximum(true);
                } catch (Exception x) {
                    System.out.println("Error: " + x);
                }
            }
        }
    }//GEN-LAST:event_catalogoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(new NimbusLookAndFeel());
                } catch (Exception e) {

                }
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JMenu catalogo;
    public static javax.swing.JButton cerrar;
    public static javax.swing.JButton iniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JMenu mantencion;
    public static javax.swing.JLabel mensajebien;
    public static javax.swing.JDesktopPane visor;
    // End of variables declaration//GEN-END:variables
}
